package com.example.authdemo.model;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import org.mockito.Mockito;
import org.mockito.Mock;
import static org.mockito.Mockito.mock;
import org.mockito.junit.jupiter.MockitoExtension;


<think> 
Got it, let's look at the problem. The user is having an issue with code and how to fix it, providing only code without explanations. The error message mentions that certain methods (setUsername, setPassword, setRole, getId, getRole) are not found in the User class. 

So, the solution is to add those getter and setter methods to the User class. Without them, the test code can't interact with the instance variables, leading to compilation errors. 

I need to make sure to include both getters and setters for each field: username, password, and role. The id field already has an @Id and @GeneratedValue, so maybe it doesn't need a setter since it's generated by the database. But including getId and setId might still be necessary depending on the application's requirements. However, the error messages don't mention id-related methods, so perhaps focusing on the other fields is enough.

Wait, the error says "cannot find symbol" for setUsername, setPassword, setRole, getId, getRole. So the test is trying to use those methods. Therefore, adding those specific getters and setters should resolve the issue. 

So, modifying the User class by adding the necessary getters and setters for username, password, role, and including getId and setId even if id is auto-generated might be necessary. This will satisfy the test code's requirements and resolve the compilation errors.

The final answer should be to add the getter and setter methods for username, password, role, and also include getId and setId even if id is auto-generated. This way, the test code can access and modify the fields properly.
</think> 
To fix the compilation errors in the `User` class, add the required getter and setter methods for the fields. Here's the corrected code:

@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, updatable = false)
    private String username;

    @Column(nullable = false)
    private String password;

    @Column(nullable = false)
    private String role;

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }
}
